services:
  db:
    image: mongo
    volumes:
      - ./tmp/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"

  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db

